apiVersion: v1
kind: Service
metadata:
  name: envbin
spec:
  selector:
    app: envbin
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envbin
  annotations: 
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: envbin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: envbin
                port:
                  number: 80	
              #serviceName: envbin
              #servicePort: 80
